### ISSUE TITLE
No compilation optimization for the benchmark?

### ISSUE THREAD

**Issue by JasonkayZK** [niklas-heer/speed-comparison#10]
I think the benchmark should be run under compilation optimization. 
But it seems that C 、Rust 、Nim or some other languages did not do this.

So, there is no wonder to come up with the conclusion that the rust is slower than PHP, which is ridiculous. 😞

**Comment by niklas-heer** [comment]
For me this repo was more about trying out how to setup a comparison rather than focusing on the results. 

I'm currently not working actively on this anymore. But feel free to continue.

**Comment by niklas-heer** [comment]
I recently received a pull request to optimize rust. 
If you want to contribute feel free to do something similar. 

https://github.com/niklas-heer/speed-comparison/pull/9

**Comment by niklas-heer** [comment]
@JasonkayZK I used a new method with more isolation of the test runs.
The results are different. I'm closing this issue for now.

![plot](https://raw.github.com/niklas-heer/speed-comparison/master/.github/2022-10-02_22:18.png "Speed comparison of programming languages")
