### ISSUE TITLE
Clojure solution like in Java

### ISSUE THREAD

**Issue by serioga** [niklas-heer/speed-comparison#55]
To compare Clojure solution with Java more correctly you can use this translation of Java code:

```clojure
(defn calc-pi-leibniz [rounds]
  (let [end (+ 2 rounds)]
    (loop [i 2 x 1.0 pi 1.0]
      (if (= i end)
        (* 4 pi)
        (let [x (- x)]
          (recur (inc i) x (+ pi (/ x (dec (* 2 i))))))))))
```
It should be about 6-7x faster.

**Comment by niklas-heer** [comment]
@serioga I appreciate the improvement. :+1: 
I'm very new to Clojure :sweat_smile: 

Do you want to create a PR, or should I add it for you? (since the [Hacktoberfest](https://hacktoberfest.com/) is going on)

**Comment by serioga** [comment]
I've created a pull request https://github.com/niklas-heer/speed-comparison/pull/56
