### ISSUE TITLE
There is a problem with visual ordering

### ISSUE THREAD

**Issue by zsz00** [niklas-heer/speed-comparison#68]
There is a problem with visual ordering: 
![image](https://user-images.githubusercontent.com/12711073/196849725-f84f1487-9910-47fb-abef-a37353163c4e.png)

**Comment by niklas-heer** [comment]
@zsz00 good point! Thank you for noticing and sharing.
I think this is due that I forgot to change the ordering of the Dataframe to min so atm it's still ordered by median.

https://github.com/niklas-heer/speed-comparison/blob/7f6b2ab038d074f1914247020c55fe2aa550625a/analyze.py#L152

https://github.com/niklas-heer/speed-comparison/blob/7f6b2ab038d074f1914247020c55fe2aa550625a/analyze.py#L34-L38
