### ISSUE TITLE
Proper Julia code is much faster than this. Embed in a function.

### ISSUE THREAD

**Issue by skanskan** [niklas-heer/speed-comparison#8]
In Julia you need to insert the code within a function.  Doing so makes the code much faster.
And you shouldn't have to include the first time execution time.

This code takes only 1.2ms in my computer, properly benchmarked with the package Benchmarktools.

```
function f() 
    rounds = parse(Int64,strip(read("rounds.txt", String)))    
    x = 1.0
    pi = 1.0

    for i in 2:(rounds + 2)
        x *= -1
        pi += x / (2 * i - 1)
    end

    pi *= 4
    print(pi)
end

```

(I have updated the read function to make it compatible with Julia 1.3.  Other packages are faster reading files)

It's not fair that you predeclare types in other languages benchmarks, such as C, and not in Julia.
You could also use @fastmath, @inbounds, @simd, and in version 1.3 you can easily create a multithreaded version (many other languages cannot do it).

**Comment by niklas-heer** [comment]
@skanskan thank you for taking the time to write this! As mentioned in my [disclaimer](https://github.com/niklas-heer/speed-comparison#disclaimer) I'm no expert in all of these languages and Julia is one of the languages I only picked up for this project. Sorry if you feel that Julia is misrepresented.

I gladly accept pull-requests but currently I don't actively work on the project anymore.

**Comment by ggorlen** [comment]
Putting the code into a function should be done in CPython as well, and possibly all languages. See [Why does Python code run faster in a function?](https://stackoverflow.com/questions/11241523/why-does-python-code-run-faster-in-a-function).

**Comment by niklas-heer** [comment]
We have new results and now Julia is faster than Python. (at least CPython)
Thus closing this issue for now.

![plot](https://raw.github.com/niklas-heer/speed-comparison/master/.github/2022-10-02_22:18.png "Speed comparison of programming languages")
